name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=arkanoid --cov-report=html --html=report.html
    - name: Run linter
      run: |
        flake8 . --max-line-length=88 --extend-ignore=E203 > flake8.txt
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
    - name: Upload linter report
      uses: actions/upload-artifact@v4
      with:
        name: linter-report
        path: flake8.txt