name: ArkanoidCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # Дебаг: вивести встановлені пакети

    - name: Lint with Flake8
      run: |
        flake8 . --max-line-length=88 --extend-ignore=E203 > flake8.txt
        cat flake8.txt  # Дебаг: показати результати

    - name: Test with Pytest
      env:
        SDL_VIDEODRIVER: dummy  # Для pygame в headless-режимі
      run: |
        pytest tests/test_arkanoid.py --cov=arkanoid --cov-report=html --html=report.html --self-contained-html
        ls -la  # Дебаг: перевірити згенеровані файли

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: arkanoid-test-report
        path: report.html
        if-no-files-found: error

    - name: Upload Flake8 report
      uses: actions/upload-artifact@v4
      with:
        name: arkanoid-flake8-report
        path: flake8.txt
        if-no-files-found: error

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: arkanoid-coverage-report
        path: htmlcov/
        if-no-files-found: error